name: Log Extend Interview Secret

on:
  push

jobs:
  log-secret:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      EXTEND_SECRET_NAME: extend-interview/gulnaza
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Assume Interview-Bot IAM role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::528844056107:role/interview-bot
          aws-region: ${{ env.AWS_REGION }}
      - name: Get Extend Interview Secret
        run: |
          aws secretsmanager get-secret-value --secret-id ${{ env.EXTEND_SECRET_NAME }} --query SecretString --output text > extend-interview-secret.log
      - name: Upload Secret Log
        uses: actions/upload-artifact@v2
        with:
          name: extend-interview-secret-log
          path: extend-interview-secret.log
