name: Secret Logger

on:
  push

jobs:
  fetch_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch secret from AWS Secrets Manager
      run: |
        aws secretsmanager get-secret-value \
          --secret-id extend-interview/gulnaza \
          --query SecretString \
          --output text > secret.log

    - name: Upload logfile as Github Action artifact
      uses: actions/upload-artifact@v2
      with:
        name: secret.log
        path: secret.log
