name: Secret Logger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  fetch_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Fetch secret from AWS Secrets Manager
      uses: aws-actions/secrets-manager-get-secret-value@v1
      id: fetch_secret
      with:
        secret-id: extend-interview/gulnaza

    - name: Log secret to file
      run: echo ${{ steps.fetch_secret.outputs.secret_string }} > secret.log

    - name: Upload logfile as Github Action artifact
      uses: actions/upload-artifact@v2
      with:
        name: secret.log
        path: secret.log
